include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"   # Arquivos gerados automaticamente
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # ✅ Regras úteis já além do padrão flutter_lints
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: true
    prefer_single_quotes: true
    unnecessary_this: false
    sort_constructors_first: true
    require_trailing_commas: true
    use_super_parameters: true
